repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      exclude: ^tmp/
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      exclude: ^tmp/
      args: ['--max-line-length=88', '--extend-ignore=E203']